### ISSUE TITLE
Docker support (or other containerizer)

### ISSUE THREAD

**Issue by steveniemitz** [mesos/kafka#270]
It seems a common theme here is people would like to see some form of containerizer support in the framework.

There are two options for implementation that I can think of: 
- Supporting the mesos containerizer + the docker image provider ([docs](http://mesos.apache.org/documentation/latest/mesos-containerizer/))
- Supporting the actual docker containerizer

The docker containerizer is being phased out as I understand, so I think it makes sense to support the mesos containerizer + docker image provider.  However, what use cases do people want to use docker for?  It seems like two requested things (besides simply using docker) are (1) custom docker volume plugins, and (2) network isolation.

(1) can be solved in the mesos containerizer using its [docker volume](http://mesos.apache.org/documentation/latest/docker-volume/) support.
(2) is trickier, but I also don't know how many people would actually use it.  Personally I've always tried to avoid docker network isolation.

Given this, the best path I see, in order, is:
1. Support launching the executor w/ docker images via the docker image provider in the mesos containerizer.  This would mean associating docker image with a broker configuration.
1. Add support for setting one or more docker volumes on a broker.
1. Possibly add support for [CNI](http://mesos.apache.org/documentation/latest/cni/) to support more advanced networking use-cases

I'd love to hear people's thoughts on this!

**Comment by LLParse** [comment]
[This repository](https://github.com/mesosphere/dcos-kafka-service) serves the same purpose and is more actively maintained, so my personal thought is to do the work there, or fork that version if mesosphere isn't accepting pull requests from the community.

**Comment by steveniemitz** [comment]
This has come up a few times, that linked framework requires running DCOS, which many people (including myself) don't want to do.

The DCOS framework also seems to have significantly less features than this one.  IMO it seems like a better idea to make this framework work in the DCOS ecosystem, but I don't really have any motivation myself to do that (again, since we don't run DCOS).

**Comment by LLParse** [comment]
Fair enough - I wasn't aware that mesosphere frameworks were so tightly coupled to DCOS.

It would be cool to see either implementations realized. Personally, I would like to see docker containerizer support, simply because my Mesos distro is dated and does not yet support the unified containerizer.

**Comment by steveniemitz** [comment]
Noted, I suspect that once the mesos containerizer + docker image provider is supported, supporting the docker containerizer will be easy as well, since most of the work is going to be around the broker configuration management, not actually launching the tasks themselves.

**Comment by h0tbird** [comment]
I am willing to test this. I run Mesos on top of CoreOS (no Java in the host). Everything I run on Mesos is using the `UCR` + `CNI`. I also use Calico and REX-Ray.

**Comment by steveniemitz** [comment]
Awesome!  That'll be a great test system.  I'll keep this updated as things move forward.

**Comment by steveniemitz** [comment]
I've opened a pull request #281 w/ initial support for launching docker images.  Some documentation is there on how to configure a broker to launch.  I'd love if people could try it out and provide feedback.  I've tested both with the docker containerizer and mesos isolator.

Note: don't forget to follow the steps [here](http://mesos.apache.org/documentation/latest/container-image/) to configure the mesos agent.

Next steps I see are:
- Support for docker volume volumes
- Support for network isolation (via CNI or docker networking)

**Comment by steveniemitz** [comment]
I've had one report so far of someone testing this (thanks @h0tbird) but it'd be nice to get more feedback before I merge it in.  If other people could try it out it'd be appreciated!

**Comment by h0tbird** [comment]
Yes I can confirm this is working for me:
```
bash-4.3# ./kafka-mesos.sh broker list
broker:
  id: 0
  active: true
  state: running
  resources: cpus:1.00, mem:2048, heap:1024, port:auto
  java-cmd: unset LD_LIBRARY_PATH && /usr/glibc-compat/sbin/ldconfig && java
  image: quay.io/kato/kafka [mesos]
  mounts:
    /opt/lib => /opt/lib [ro]
  jvm-options: -XX:+PrintCommandLineFlags -verbose:class
  failover: delay:1m, max-delay:10m
  stickiness: period:10m, hostname:worker-1.cell-1.dub.xnood.com
  task: 
    id: kafka-0-67ff07ee-867a-44f5-83ec-18956df885f9
    state: running
    endpoint: worker-1.cell-1.dub.xnood.com:31000
  metrics: 
    collected: 1970-01-01 00:00:00Z
    under-replicated-partitions: 0
    offline-partitions-count: 0
    is-active-controller: 0

bash-4.3# echo "test" | kafkacat -P -b "worker-1:31000" -t testTopic -p 0
bash-4.3# kafkacat -C -b "worker-1:31000" -t testTopic -p 0 -e
test
test
% Reached end of topic testTopic [0] at offset 2: exiting
```

I am looking forward to IP per container (via CNI).
