### ISSUE TITLE
Broker options not coming back on API status calls

### ISSUE THREAD

**Issue by sherzberg** [mesos/kafka#71]
Are their defaults set for broker options like `jvm-options`? If so, can these always be returned by the `/api/brokers/status` API call?

They appear to be only returned when manually set via the cli or api.

**Comment by joestein** [comment]
the only default is the xmx (heap) which is another explicit flag. the rest you have to set them (see below) and when you do, they come back on the CLI and REST API both (including the heap though in another field)

e.g. 

```
# ./kafka-mesos.sh add 0 --jvm-options -XX:PermSize=48m
Broker added

broker:
  id: 0
  active: false
  state: stopped
  resources: cpus:1.00, mem:2048, heap:1024, port:auto
  jvm-options: -XX:PermSize=48m
  failover: delay:10s, max-delay:60s

# ./kafka-mesos.sh status
Cluster status received

cluster:
  brokers:
    id: 0
    active: false
    state: stopped
    resources: cpus:1.00, mem:2048, heap:1024, port:auto
    jvm-options: -XX:PermSize=48m
    failover: delay:10s, max-delay:60s

# curl "http://localhost:7000/api/brokers/status"
{"brokers" : [{"id" : "0", "mem" : 2048, "jvmOptions" : "-XX:PermSize=48m", "cpus" : 1.0, "heap" : 1024, "failover" : {"delay" : "10s", "maxDelay" : "60s"}, "active" : false}], "frameworkId" : "20150707-201236-84082880-5050-18983-0001"}
```
